program WhaticketIW;
uses
  FastMM4,
  IWRtlFix,
  IWJclStackTrace,
  IWJclDebug,
  IWStartHSys,
  uBase in '..\Source\base\uBase.pas' {FrmBase: TIWAppForm},
  ServerController in 'ServerController.pas' {IWServerController: TIWServerControllerBase},
  UserSessionUnit in 'UserSessionUnit.pas' {IWUserSession: TIWUserSessionBase},
  Buttons.Icons in '..\Source\BootsTrap\Componentes\Buttons\Buttons.Icons.pas',
  uFrmLogin in '..\Source\Pages\Login\uFrmLogin.pas' {FrmLogin: TIWAppForm},
  uFrmDashboard in '..\Source\Pages\FrmDashboard\uFrmDashboard.pas' {FrmDashboard: TIWAppForm},
  uFrmSettings in '..\Source\Pages\Settings\uFrmSettings.pas' {FrmSettings: TIWAppForm},
  Database.DAO.Menu in '..\Source\DataBase\DAO\Database.DAO.Menu.pas',
  Tipos.Types in '..\Source\Types\Tipos.Types.pas',
  uFrmAgendamentos in '..\Source\Pages\Agendamentos\uFrmAgendamentos.pas' {FrmAgendamentos: TIWAppForm},
  Dao.Agendamentos in '..\Source\DataBase\DAO\Dao.Agendamentos.pas',
  Functions.Strings in '..\Source\Funcoes\Functions.Strings.pas',
  Integracao.Discord in '..\Source\Integracoes\Integracao.Discord.pas',
  App.Config in '..\Source\Config\App.Config.pas',
  Functions.Boolean in '..\Source\Funcoes\Functions.Boolean.pas',
  Entidade.Agendamentos in '..\Source\DataBase\ENTITY\Entidade.Agendamentos.pas',
  uFrmAtendimento in '..\Source\Pages\Atendimento\uFrmAtendimento.pas' {FrmAtendimento: TIWAppForm},
  uFrmContatos in '..\Source\Pages\Contatos\uFrmContatos.pas' {FrmContatos: TIWAppForm},
  Entidade.Contatos in '..\Source\DataBase\ENTITY\Entidade.Contatos.pas',
  Dao.Contatos in '..\Source\DataBase\DAO\Dao.Contatos.pas',
  uFrmTags in '..\Source\Pages\Tags\uFrmTags.pas' {FrmTags: TIWAppForm},
  Entidade.Tags in '..\Source\DataBase\ENTITY\Entidade.Tags.pas',
  Dao.Tags in '..\Source\DataBase\DAO\Dao.Tags.pas',
  uFrmFilas in '..\Source\Pages\Filas\uFrmFilas.pas' {FrmFilas: TIWAppForm},
  Entidade.Filas in '..\Source\DataBase\ENTITY\Entidade.Filas.pas',
  Dao.Filas in '..\Source\DataBase\DAO\Dao.Filas.pas',
  uFrmRespostas in '..\Source\Pages\Respostas\uFrmRespostas.pas' {FrmRespostas: TIWAppForm},
  Entidade.Respostas in '..\Source\DataBase\ENTITY\Entidade.Respostas.pas',
  Dao.Respostas in '..\Source\DataBase\DAO\Dao.Respostas.pas',
  uFrmKanban in '..\Source\Pages\Kanban\uFrmKanban.pas' {FrmKanban: TIWAppForm},
  uFrmTarefas in '..\Source\Pages\Tarefas\uFrmTarefas.pas' {FrmTarefas: TIWAppForm},
  uFrmChat in '..\Source\Pages\Chat\uFrmChat.pas' {FrmChat: TIWAppForm},
  uFrmAjuda in '..\Source\Pages\Ajuda\uFrmAjuda.pas' {FrmAjuda: TIWAppForm},
  uFrmInformativo in '..\Source\Pages\Informativo\uFrmInformativo.pas' {FrmInformativo: TIWAppForm},
  Entidade.Informativo in '..\Source\DataBase\ENTITY\Entidade.Informativo.pas',
  Dao.Informativo in '..\Source\DataBase\DAO\Dao.Informativo.pas',
  uFrmConexoes in '..\Source\Pages\Conexoes\uFrmConexoes.pas' {FrmConexoes: TIWAppForm},
  Dao.Conexao in '..\Source\DataBase\DAO\Dao.Conexao.pas',
  uFrmUsuario in '..\Source\Pages\Usuarios\uFrmUsuario.pas' {FrmUsuario: TIWAppForm},
  Dao.Usuario in '..\Source\DataBase\DAO\Dao.Usuario.pas',
  uPopulaCrud in '..\Source\DataBase\uPopulaCrud.pas',
  Bootstrap.SweetAlert2 in '..\Source\BootsTrap\Componentes\Alert\Bootstrap.SweetAlert2.pas',
  Entidade.Usuarios in '..\Source\DataBase\ENTITY\Entidade.Usuarios.pas',
  Entidade.Conexao in '..\Source\DataBase\ENTITY\Entidade.Conexao.pas',
  Functions.DataBase in '..\Source\Funcoes\Functions.DataBase.pas',
  Entidade.Configuracoes in '..\Source\DataBase\ENTITY\Entidade.Configuracoes.pas',
  Dao.Configuracoes in '..\Source\DataBase\DAO\Dao.Configuracoes.pas',
  uFrmConfiguracoes in '..\Source\Pages\Configuracoes\uFrmConfiguracoes.pas' {FrmConfiguracoes: TIWAppForm},
  IW.Content.API in '..\Source\Integracoes\IW.Content.API.pas',
  Dao.Messages in '..\Source\DataBase\DAO\Dao.Messages.pas',
  Entidade.Messages in '..\Source\DataBase\ENTITY\Entidade.Messages.pas',
  Functions.Rest in '..\Source\Funcoes\Functions.Rest.pas',
  WebHook.MessageText in '..\Source\WebHooks\WebHook.MessageText.pas',
  Dao.ProcessaMensagem in '..\Source\DataBase\DAO\Dao.ProcessaMensagem.pas',
  WebHook.MessageProfileUpdate in '..\Source\WebHooks\WebHook.MessageProfileUpdate.pas',
  WebHook.MessageAudio in '..\Source\WebHooks\WebHook.MessageAudio.pas',
  WebHook.MessageImage in '..\Source\WebHooks\WebHook.MessageImage.pas',
  Functions.IW in '..\Source\Funcoes\Functions.IW.pas',
  WebHook.MessageVideo in '..\Source\WebHooks\WebHook.MessageVideo.pas',
  WebHook.MessageArquivos in '..\Source\WebHooks\WebHook.MessageArquivos.pas',
  Integracao.API.Evolution in '..\Source\Integracoes\Integracao.API.Evolution.pas',
  Integracao.Evolution.CreateInstance in '..\Source\Integracoes\Integracao.Evolution.CreateInstance.pas',
  Entidade.Tasks in '..\Source\DataBase\ENTITY\Entidade.Tasks.pas',
  Dao.Tasks in '..\Source\DataBase\DAO\Dao.Tasks.pas',
  Entidade.Tickets in '..\Source\DataBase\ENTITY\Entidade.Tickets.pas',
  Dao.Tickets in '..\Source\DataBase\DAO\Dao.Tickets.pas',
  uWorkerThread in '..\uWorkerThread.pas',
  BootsTrap.Cards in '..\Source\BootsTrap\Componentes\Cards\BootsTrap.Cards.pas',
  Dao.Dashboard in '..\Source\DataBase\DAO\Dao.Dashboard.pas';

{$R *.res}
begin
   // Teste de Commite
  {$IFDEF DEBUG}
  TIWStartHSys.Execute(True);
  {$ELSE}
  TIWStartHSys.Execute(false);
  {$ENDIF}

end.
